### ISSUE TITLE
Issue: LEDGER_CANISTER_ID is not defined

### ISSUE THREAD

**Issue by danielterwiel** [internet-identity-labs/NFID-SDK#205]
**Describe the bug**
Opening the local deployment of NFID results in a blank screen and an Error thrown in the console

**To Reproduce**

Clone latest NFID repo. And execute the following commands

```sh
yarn
yarn nfid:setup
yarn nfid:start
yarn nfid:tunnel
```

**Expected behavior**
NFID frontend is shown

**Error in console**
```
Uncaught ReferenceError: LEDGER_CANISTER_ID is not defined
    at actors.ts:37:14
    at index.tsx:42:11
    at index.tsx:42:11
(anonymous) @ actors.ts:37
(anonymous) @ index.tsx:42
(anonymous) @ index.tsx:42
index.js:551 
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Arc (Chromium based)

**Additional context**

Now, I've got a local ledger so I deployed that canister and assigned its id to LEDGER_CANISTER_ID using the .env.local file. But that doesn't get picked up here

**Comment by jorgenbuilder** [comment]
I ran into this issue while attemping to setup NFID for local development. It seems there are some constants that are missing from `build/nfid/index.ts`, and adding them solves the immediate issue:

```
(window as any).LEDGER_CANISTER_ID = "ryjl3-tyaaa-aaaaa-aaaba-cai";
(window as any).CYCLES_MINTER_CANISTER_ID = "rkp4c-7iaaa-aaaaa-aaaca-cai";
(window as any).CURRCONV_TOKEN = "THIS IS A SECRET";
```

Unfortunately this leads to another couple of errors, when trying to authenticate with google:

```
P
OST http://localhost:9090/signin 404 (Not Found)
```

**Comment by plitzenberger** [comment]
fixed on latest
