### ISSUE TITLE
Custom elements

### ISSUE THREAD

**Issue by lastmjs** [internet-identity-labs/NFID-SDK#21]
@plitzenberger I know we'll be discussing this soon. I'm looking through the examples, and everything is React-specific. I don't use React and many others don't as well, so it's sad to see this. Of course you plan to add integrations for other frameworks. But all of this work is somewhat unnecessary.

Instead of creating React components you could create web components. These are official native custom HTML elements that look, feel, and behave like any other HTML element. You can plug them into many frameworks just like any other html element, passing in properties, attributes, listening to events, etc. React 19 should have full support for custom element interop as well. See here for interop of many popular frameworks with custom elements: https://custom-elements-everywhere.com/

Instead of creating React components, Vue components, Angular components, Svelte components, etc you could just create nfid-elements that are essentially the same thing, and let the developers choose to drop them into a framework of their choice. And the developer experience of custom elements IMO is very slick. You can see a simple example app I've built for the IC using custom elements here: https://github.com/sudograph/sudograph/tree/main/examples/basic/canisters/frontend

I've used them for ~5 years now for nearly every project I've worked on.

So instead of `<Iframe />` and `<InternetIdentityProvider />` which can only be used in a React application, you could instead provide developers native custom HTML elements `<nfid-iframe></nfid-iframe>` and `nfid-ii-provider></nfid-ii-provider>` that provide the exact some behavior and possibly a better DX to developers, without restricting them to one framework.

Custom elements will work with all of the following: `Vue`, `React 19`, `Angular`, `AngularJS`, `Svelte`, `Preact`, `Stencil`, `Dojo` and more.

**Comment by plitzenberger** [comment]
Hey @lastmjs, thanks for the review and your feedback. I'm with you. The amount of integrations would be crazy and indeed unnecessary with native components. I'm hoping to get some heads up next week in our meeting.

**Comment by plitzenberger** [comment]
And btw, it's not getting clear from our docs so far. You don't need our plugin at all to integrate NFID as it uses the exact same interface as II. So you just replace the `authClient` prop `identityProvider: "https://identity.ic0.app/#authorize" with one of our urls: 

- `IFRAME MODE`: https://3y5ko-7qaaa-aaaal-aaaaq-cai.ic0.app/iframe-authenticate/?applicationName=YOUR_APPLICATION_NAME
- `NEW WINDOW MODE`: https://3y5ko-7qaaa-aaaal-aaaaq-cai.ic0.app/authenticate/?applicationName=YOUR_APPLICATION_NAME

With `@dfinity/auth-client": "0.11.0"` you can also pass the pop up window configuration like so: 

```
authClient.login({
   windowOpenerFeatures: `toolbar=0,location=0,menubar=0,width=400,height=600,left=${
        window.screen.width / 2 - 200
   }, top=${window.screen.height / 2 - 300}`
})
```

**Comment by lastmjs** [comment]
I have set my identityProvider to `https://3y5ko-7qaaa-aaaal-aaaaq-cai.ic0.app/authenticate/?applicationName=multisig_vault` and I get a new tab, not a new window

**Comment by lastmjs** [comment]
When I add `windowOpenerFeatures` like described above it does open in a new window...but is that necessary? What is the simplest possible way to get a window to open?

**Comment by plitzenberger** [comment]
Unfortunately this is the only option we've found so far. This is because the `@dfintity/auth-client` [opens the window](https://github.com/dfinity/agent-js/blob/main/packages/auth-client/src/index.ts#L407-L409). We provide two different routes as they need to behave differently.
